describe('Test case 4', () => {
    it('TC4', () => {
        cy.visit('https://demo.bnz.co.nz/client/payees',{ headers: { "Accept-Encoding": "gzip, deflate" } })
        cy.get('button').contains('Add').click()
        cy.get('[id="ComboboxInput-apm-name"]').type('S Goswami').type('{enter}')
        cy.get('[id="apm-bank"]').type('0212340123456001')
        cy.get('button.js-submit.Button.Button--primary.Button--disabled').contains('Add').click()
        cy.get('#notification').contains('Payee added')
        cy.get('[aria-label="Sort by payee name A to Z selected. Select again to reverse order."]')
        .contains("Name")
        .should("be.visible")
        cy.get('ul > li:nth-child(1) > div').should('have.attr','aria-label', 'Auckland Council . Account number 01-0001-0000001-001. button')
        cy.get('[aria-label="Sort by payee name A to Z selected. Select again to reverse order."]')
        .contains("Name").click()
        cy.get('[aria-label="Sort by payee name Z to A selected. Select again to reverse order."]')
        .contains("Name")
        .should("be.visible")
        cy.get('ul > li:nth-child(6) > div').should('have.attr','aria-label', 'Auckland Council . Account number 01-0001-0000001-001. button')
        })
    })